---
abstract: 'Archive-Tar-Wrapper minus IPC::Run, IO::Pty'
author:
  - 'Krzysztof Bieszczad <kbsw@hushmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archive-Tar-Wrapper-IPC-Cmd
requires:
  Cwd: 0
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IPC::Cmd: 0
  Log::Log4perl: 0
version: 0.22
